POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST http://localhost:8081/favoriteMovies/addFavoriteMovie
Content-Type: application/json 

{
    "title": "The Super Mario Bros. Movie",
    "year": "2023",
    "id": "tt6718170",
    "type": "movie",
    "poster": "https://m.media-amazon.com/images/M/MV5BOGZlN2EzOTYtMzUzOS00NTM3LTg0MTQtZDVjZGM4YmJlNWNhXkEyXkFqcGc@._V1_SX300.jpg",
    "userId": "67cb2cb6f089a2d609f93ec2"
}

###
POST http://localhost:8081/favoriteMovies/addFavoriteMovie
Content-Type: application/json 

{
    "title": "The Super Mario Bros. Movie",
    "year": "2023",
    "id": "tt6718170",
    "type": "movie",
    "poster": "https://m.media-amazon.com/images/M/MV5BOGZlN2EzOTYtMzUzOS00NTM3LTg0MTQtZDVjZGM4YmJlNWNhXkEyXkFqcGc@._V1_SX300.jpg",
    "userId": "67cb2cb6f089a2d609f93ec2"
}


###
GET http://localhost:8081/favoriteMovies/getAll
Content-Type: application/json

###
DELETE  http://localhost:8081/favoriteMovies/deleteFavoriteMoviesById/67cbd4f9db2c953730dba126

###
GET http://localhost:8081/favoriteMovies/getAll
Content-Type: application/json

###
PUT http://localhost:8081/favoriteMovies/updateFavoriteMovie
Content-Type: application/json 

{
    "userId" : "67cb2cb6f089a2d609f93ec2",
    "title": "The Simpsons Movie",
    "year": "2007",
    "id": "tt0462538",
    "type": "movie",
    "poster": "https://m.media-amazon.com/images/M/MV5BMzIxN2IzOGItOTcyZi00MTkzLWE4ZjktZTdlOWFiYWE4NzlmXkEyXkFqcGc@._V1_SX300.jpg"
}
